/// <reference path="../pb_data/types.d.ts" />

const DATA = [
  {
    "titel": "Quick TCD",
    "beschreibung": "1\nInstallation vorbereiten\nUnterbrich die Stromversorgung der Strahlruder.\n\n2\nStecker der Strahlruder freilegen\nLege die Stecker der Strahlruder frei. Diese befinden sich meistens im Steuerstand in der Nähe des Bedienpanels für die Strahlruder.\n\n3\nStecker trennen\nLöse die Stecker für Bug- und/oder Hecksteuerung.\n\n4\nTCU dazwischenklemmen\nSchließe jetzt deine TCU mithilfe des mitgeliefertenKabelbaums an. Achte darauf, dass die Stecker ordnungsgemäß verbunden sind und fest sitzen. Details zu den Steckverbindungen und ausführlichere Informationen zum Anschluss findest du in der jeweiligen PDF-Anleitung zu deinem Bootsantrieb.\n\nAchtung: Wenn dein Boot mit Bug- und Heckstrahlruder ausgestattet ist, stelle sicher, dass die Heck- und Bugsteuerungen jeweils korrekt verbunden sind.\n\n5\nApp installieren\nLade jetzt die SMARTDOCK App im Google Play Store oder im App Store herunter. Beim Start der App wird eine Schaltfläche zur automatischen Einrichtung eingeblendet. Tippe an dieser Stelle noch nicht darauf.\n\n6\nKopplungsmodus der TCU starten\nStelle die Spannungsversorgung über den Hauptschalter wieder her. Solange kein Handy mit der TCU gekoppelt ist, startet der Kopplungsmodus automatisch. Dies erkennst du daran, dass die LED dauerhaft leuchtet.\n\nHINWEIS: Um die TCU mit einem weiteren Handy zu koppeln, rufst du den Kopplungsmodus der TCU manuell auf, indem du den Taster am Gerät so lange drückst, bis die LED der TCU dauerhaft leuchtet (Kopplungsmodus aktiv).\n\n7\nApp mit TCU koppeln\nTippe jetzt in der App auf die Schaltfläche \"Starten\", um mit der automatischen Einrichtung zu beginnen. Nachdem die App deine Geräte erkannt hat, erhältst du ein Tutorial und wirst durch die Einrichtung geführt, um die Feineinstellungen vorzunehmen.\n\nDeine App ist jetzt gekoppelt und einsatzbereit. Nutze gerne auch den Demo-Modus, um dich mit den Steuerelementen vertraut zu machen.",
    "titel_en": "Quick TCD"
  },
  {
    "titel": "Vetus",
    "beschreibung": "1\nInstallation vorbereiten\nUnterbrich die Stromversorgung der Strahlruder.\n\n2\nStecker der Strahlruder freilegen\nLege die Stecker der Strahlruder frei. Diese befinden sich meistens im Steuerstand in der Nähe des Bedienpanels für die Strahlruder.\n\n3\nStecker trennen\nLöse die Stecker für Bug- und/oder Hecksteuerung.\n\n4\nTCU dazwischenklemmen\nSchließe jetzt deine TCU mithilfe des mitgeliefertenKabelbaums an. Achte darauf, dass die Stecker ordnungsgemäß verbunden sind und fest sitzen. Details zu den Steckverbindungen und ausführlichere Informationen zum Anschluss findest du in der jeweiligen PDF-Anleitung zu deinem Bootsantrieb.\n\nAchtung: Wenn dein Boot mit Bug- und Heckstrahlruder ausgestattet ist, stelle sicher, dass die Heck- und Bugsteuerungen jeweils korrekt verbunden sind.\n\n5\nApp installieren\nLade jetzt die SMARTDOCK App im Google Play Store oder im App Store herunter. Beim Start der App wird eine Schaltfläche zur automatischen Einrichtung eingeblendet. Tippe an dieser Stelle noch nicht darauf.\n\n6\nKopplungsmodus der TCU starten\nStelle die Spannungsversorgung über den Hauptschalter wieder her. Solange kein Handy mit der TCU gekoppelt ist, startet der Kopplungsmodus automatisch. Dies erkennst du daran, dass die LED dauerhaft leuchtet.\n\nHINWEIS: Um die TCU mit einem weiteren Handy zu koppeln, rufst du den Kopplungsmodus der TCU manuell auf, indem du den Taster am Gerät so lange drückst, bis die LED der TCU dauerhaft leuchtet (Kopplungsmodus aktiv).\n\n7\nApp mit TCU koppeln\nTippe jetzt in der App auf die Schaltfläche \"Starten\", um mit der automatischen Einrichtung zu beginnen. Nachdem die App deine Geräte erkannt hat, erhältst du ein Tutorial und wirst durch die Einrichtung geführt, um die Feineinstellungen vorzunehmen.\n\nDeine App ist jetzt gekoppelt und einsatzbereit. Nutze gerne auch den Demo-Modus, um dich mit den Steuerelementen vertraut zu machen.",
    "titel_en": "Vetus"
  },
  {
    "titel": "Sleipner Side Power",
    "beschreibung": "1\nInstallation vorbereiten\nUnterbrich die Stromversorgung der Strahlruder.\n\n2\nStecker der Strahlruder freilegen\nLege die Stecker der Strahlruder frei. Diese befinden sich meistens im Steuerstand in der Nähe des Bedienpanels für die Strahlruder.\n\n3\nStecker trennen\nLöse die Stecker für Bug- und/oder Hecksteuerung.\n\n4\nTCU dazwischenklemmen\nSchließe jetzt deine TCU mithilfe des mitgeliefertenKabelbaums an. Achte darauf, dass die Stecker ordnungsgemäß verbunden sind und fest sitzen. Details zu den Steckverbindungen und ausführlichere Informationen zum Anschluss findest du in der jeweiligen PDF-Anleitung zu deinem Bootsantrieb.\n\nAchtung: Wenn dein Boot mit Bug- und Heckstrahlruder ausgestattet ist, stelle sicher, dass die Heck- und Bugsteuerungen jeweils korrekt verbunden sind.\n\n5\nApp installieren\nLade jetzt die SMARTDOCK App im Google Play Store oder im App Store herunter. Beim Start der App wird eine Schaltfläche zur automatischen Einrichtung eingeblendet. Tippe an dieser Stelle noch nicht darauf.\n\n6\nKopplungsmodus der TCU starten\nStelle die Spannungsversorgung über den Hauptschalter wieder her. Solange kein Handy mit der TCU gekoppelt ist, startet der Kopplungsmodus automatisch. Dies erkennst du daran, dass die LED dauerhaft leuchtet.\n\nHINWEIS: Um die TCU mit einem weiteren Handy zu koppeln, rufst du den Kopplungsmodus der TCU manuell auf, indem du den Taster am Gerät so lange drückst, bis die LED der TCU dauerhaft leuchtet (Kopplungsmodus aktiv).\n\n7\nApp mit TCU koppeln\nTippe jetzt in der App auf die Schaltfläche \"Starten\", um mit der automatischen Einrichtung zu beginnen. Nachdem die App deine Geräte erkannt hat, erhältst du ein Tutorial und wirst durch die Einrichtung geführt, um die Feineinstellungen vorzunehmen.\n\nDeine App ist jetzt gekoppelt und einsatzbereit. Nutze gerne auch den Demo-Modus, um dich mit den Steuerelementen vertraut zu machen.",
    "titel_en": "Sleipner Side Power"
  },
  {
    "titel": "Universell",
    "beschreibung": "1\nInstallation vorbereiten\nUnterbrich die Stromversorgung der Strahlruder.\n\n2\nStecker der Strahlruder freilegen\nLege die Stecker der Strahlruder frei. Diese befinden sich meistens im Steuerstand in der Nähe des Bedienpanels für die Strahlruder.\n\n3\nStecker trennen\nLöse die Stecker für Bug- und/oder Hecksteuerung.\n\n4\nTCU dazwischenklemmen\nSchließe jetzt deine TCU mithilfe des mitgeliefertenKabelbaums an. Achte darauf, dass die Stecker ordnungsgemäß verbunden sind und fest sitzen. Details zu den Steckverbindungen und ausführlichere Informationen zum Anschluss findest du in der jeweiligen PDF-Anleitung zu deinem Bootsantrieb.\n\nAchtung: Wenn dein Boot mit Bug- und Heckstrahlruder ausgestattet ist, stelle sicher, dass die Heck- und Bugsteuerungen jeweils korrekt verbunden sind.\n\n5\nApp installieren\nLade jetzt die SMARTDOCK App im Google Play Store oder im App Store herunter. Beim Start der App wird eine Schaltfläche zur automatischen Einrichtung eingeblendet. Tippe an dieser Stelle noch nicht darauf.\n\n6\nKopplungsmodus der TCU starten\nStelle die Spannungsversorgung über den Hauptschalter wieder her. Solange kein Handy mit der TCU gekoppelt ist, startet der Kopplungsmodus automatisch. Dies erkennst du daran, dass die LED dauerhaft leuchtet.\n\nHINWEIS: Um die TCU mit einem weiteren Handy zu koppeln, rufst du den Kopplungsmodus der TCU manuell auf, indem du den Taster am Gerät so lange drückst, bis die LED der TCU dauerhaft leuchtet (Kopplungsmodus aktiv).\n\n7\nApp mit TCU koppeln\nTippe jetzt in der App auf die Schaltfläche \"Starten\", um mit der automatischen Einrichtung zu beginnen. Nachdem die App deine Geräte erkannt hat, erhältst du ein Tutorial und wirst durch die Einrichtung geführt, um die Feineinstellungen vorzunehmen.\n\nDeine App ist jetzt gekoppelt und einsatzbereit. Nutze gerne auch den Demo-Modus, um dich mit den Steuerelementen vertraut zu machen.",
    "titel_en": "Universal"
  },
  {
    "titel": "Installation von SMARTDOCK für Yamaha-Antriebe mit Joystick",
    "beschreibung": "SCHRITT 1: Sicherheitshinweise\n- Stellen Sie sicher, dass der Motor ausgeschaltet ist und sich abgekühlt hat\n- Tragen Sie geeignete Schutzausrüstung (Handschuhe, Schutzbrille)\n- Arbeiten Sie in einer gut belüfteten Umgebung\n- Lesen Sie alle Anweisungen vor Beginn durch\n\nSCHRITT 2: Vorbereitung\n- Sammeln Sie alle erforderlichen Werkzeuge und Materialien\n- Überprüfen Sie, dass alle Komponenten des SMARTDOCK-Systems vorhanden sind\n- Inspizieren Sie die Komponenten auf Beschädigungen\n\nSCHRITT 3: Elektrische Verbindungen\n- Trennen Sie die Batterie vom Motor\n- Identifizieren Sie die Joystick-Anschlüsse am Yamaha-Antrieb\n- Verbinden Sie das SMARTDOCK-Steuermodul gemäß dem Schaltplan\n- Sichern Sie alle Kabelverbindungen mit Kabelbindern\n\nSCHRITT 4: Mechanische Installation\n- Montieren Sie das SMARTDOCK-Gehäuse an einem geschützten Ort\n- Verwenden Sie die mitgelieferten Befestigungsmaterialien\n- Stellen Sie sicher, dass das Gehäuse vor Wasser und Spritzwasser geschützt ist\n\nSCHRITT 5: App-Installation und Kopplung\n- Laden Sie die SMARTDOCK-App aus dem App Store oder Google Play Store herunter\n- Öffnen Sie die App und folgen Sie dem Einrichtungsassistenten\n- Aktivieren Sie Bluetooth auf Ihrem Smartphone\n- Suchen Sie nach dem SMARTDOCK-Gerät in der App\n- Koppeln Sie das Gerät durch Eingabe des Pairing-Codes (siehe Produktetikett)\n\nSCHRITT 6: Kalibrierung und Tests\n- Verbinden Sie die Batterie wieder mit dem Motor\n- Starten Sie den Motor und führen Sie einen Funktionstest durch\n- Überprüfen Sie alle Joystick-Funktionen über die App\n- Kalibrieren Sie die Steuerung nach Bedarf\n\nSCHRITT 7: Abschluss und Dokumentation\n- Überprüfen Sie alle Verbindungen ein letztes Mal\n- Dokumentieren Sie die Installation mit Fotos\n- Bewahren Sie diese Anleitung für zukünftige Referenz auf\n- Registrieren Sie Ihr Gerät auf der SMARTDOCK-Website für Support",
    "titel_en": "Installation of SMARTDOCK for Yamaha drives with a joystick"
  },
  {
    "titel": "Installation von SMARTDOCK für Mercury/Mercruiser-Antriebe mit Joystick",
    "beschreibung": "SCHRITT 1: Sicherheitshinweise\n- Stellen Sie sicher, dass der Motor ausgeschaltet ist und sich abgekühlt hat\n- Tragen Sie geeignete Schutzausrüstung (Handschuhe, Schutzbrille)\n- Arbeiten Sie in einer gut belüfteten Umgebung\n- Lesen Sie alle Anweisungen vor Beginn durch\n\nSCHRITT 2: Vorbereitung\n- Sammeln Sie alle erforderlichen Werkzeuge und Materialien\n- Überprüfen Sie, dass alle Komponenten des SMARTDOCK-Systems vorhanden sind\n- Inspizieren Sie die Komponenten auf Beschädigungen\n\nSCHRITT 3: Elektrische Verbindungen\n- Trennen Sie die Batterie vom Motor\n- Identifizieren Sie die Joystick-Anschlüsse am Mercury/Mercruiser-Antrieb\n- Verbinden Sie das SMARTDOCK-Steuermodul gemäß dem Schaltplan\n- Sichern Sie alle Kabelverbindungen mit Kabelbindern\n\nSCHRITT 4: Mechanische Installation\n- Montieren Sie das SMARTDOCK-Gehäuse an einem geschützten Ort\n- Verwenden Sie die mitgelieferten Befestigungsmaterialien\n- Stellen Sie sicher, dass das Gehäuse vor Wasser und Spritzwasser geschützt ist\n\nSCHRITT 5: App-Installation und Kopplung\n- Laden Sie die SMARTDOCK-App aus dem App Store oder Google Play Store herunter\n- Öffnen Sie die App und folgen Sie dem Einrichtungsassistenten\n- Aktivieren Sie Bluetooth auf Ihrem Smartphone\n- Suchen Sie nach dem SMARTDOCK-Gerät in der App\n- Koppeln Sie das Gerät durch Eingabe des Pairing-Codes (siehe Produktetikett)\n\nSCHRITT 6: Kalibrierung und Tests\n- Verbinden Sie die Batterie wieder mit dem Motor\n- Starten Sie den Motor und führen Sie einen Funktionstest durch\n- Überprüfen Sie alle Joystick-Funktionen über die App\n- Kalibrieren Sie die Steuerung nach Bedarf\n\nSCHRITT 7: Abschluss und Dokumentation\n- Überprüfen Sie alle Verbindungen ein letztes Mal\n- Dokumentieren Sie die Installation mit Fotos\n- Bewahren Sie diese Anleitung für zukünftige Referenz auf\n- Registrieren Sie Ihr Gerät auf der SMARTDOCK-Website für Support",
    "titel_en": "Installation of SMARTDOCK for Mercury/Mercruiser engines with a joystick"
  },
  {
    "titel": "Installation von SMARTDOCK für Volvo Penta-Antriebe Doppelantrieb ohne Joystick EVC -D/-E/2.0",
    "beschreibung": "SCHRITT 1: Sicherheitshinweise\n- Stellen Sie sicher, dass der Motor ausgeschaltet ist und sich abgekühlt hat\n- Tragen Sie geeignete Schutzausrüstung (Handschuhe, Schutzbrille)\n- Arbeiten Sie in einer gut belüfteten Umgebung\n- Lesen Sie alle Anweisungen vor Beginn durch\n\nSCHRITT 2: Vorbereitung\n- Sammeln Sie alle erforderlichen Werkzeuge und Materialien\n- Überprüfen Sie, dass alle Komponenten des SMARTDOCK-Systems vorhanden sind\n- Inspizieren Sie die Komponenten auf Beschädigungen\n\nSCHRITT 3: Elektrische Verbindungen\n- Trennen Sie die Batterie vom Motor\n- Identifizieren Sie die EVC-Anschlüsse am Volvo Penta-Doppelantrieb\n- Verbinden Sie das SMARTDOCK-Steuermodul gemäß dem Schaltplan für EVC -D/-E/2.0\n- Sichern Sie alle Kabelverbindungen mit Kabelbindern\n\nSCHRITT 4: Mechanische Installation\n- Montieren Sie das SMARTDOCK-Gehäuse an einem geschützten Ort\n- Verwenden Sie die mitgelieferten Befestigungsmaterialien\n- Stellen Sie sicher, dass das Gehäuse vor Wasser und Spritzwasser geschützt ist\n\nSCHRITT 5: App-Installation und Kopplung\n- Laden Sie die SMARTDOCK-App aus dem App Store oder Google Play Store herunter\n- Öffnen Sie die App und folgen Sie dem Einrichtungsassistenten\n- Aktivieren Sie Bluetooth auf Ihrem Smartphone\n- Suchen Sie nach dem SMARTDOCK-Gerät in der App\n- Koppeln Sie das Gerät durch Eingabe des Pairing-Codes (siehe Produktetikett)\n\nSCHRITT 6: Kalibrierung und Tests\n- Verbinden Sie die Batterie wieder mit dem Motor\n- Starten Sie den Motor und führen Sie einen Funktionstest durch\n- Überprüfen Sie alle Steuerfunktionen über die App\n- Kalibrieren Sie die Steuerung nach Bedarf\n\nSCHRITT 7: Abschluss und Dokumentation\n- Überprüfen Sie alle Verbindungen ein letztes Mal\n- Dokumentieren Sie die Installation mit Fotos\n- Bewahren Sie diese Anleitung für zukünftige Referenz auf\n- Registrieren Sie Ihr Gerät auf der SMARTDOCK-Website für Support",
    "titel_en": "Installation of SMARTDOCK for Volvo Penta twin-drive systems without a joystick (EVC -D/-E/2.0)"
  },
  {
    "titel": "Installation von SMARTDOCK für Volvo Penta-Antriebe Doppelantrieb mit Joystick EVC -C/-D/-E/2.0",
    "beschreibung": "SCHRITT 1: Sicherheitshinweise\n- Stellen Sie sicher, dass der Motor ausgeschaltet ist und sich abgekühlt hat\n- Tragen Sie geeignete Schutzausrüstung (Handschuhe, Schutzbrille)\n- Arbeiten Sie in einer gut belüfteten Umgebung\n- Lesen Sie alle Anweisungen vor Beginn durch\n\nSCHRITT 2: Vorbereitung\n- Sammeln Sie alle erforderlichen Werkzeuge und Materialien\n- Überprüfen Sie, dass alle Komponenten des SMARTDOCK-Systems vorhanden sind\n- Inspizieren Sie die Komponenten auf Beschädigungen\n\nSCHRITT 3: Elektrische Verbindungen\n- Trennen Sie die Batterie vom Motor\n- Identifizieren Sie die Joystick- und EVC-Anschlüsse am Volvo Penta-Doppelantrieb\n- Verbinden Sie das SMARTDOCK-Steuermodul gemäß dem Schaltplan für EVC -C/-D/-E/2.0\n- Sichern Sie alle Kabelverbindungen mit Kabelbindern\n\nSCHRITT 4: Mechanische Installation\n- Montieren Sie das SMARTDOCK-Gehäuse an einem geschützten Ort\n- Verwenden Sie die mitgelieferten Befestigungsmaterialien\n- Stellen Sie sicher, dass das Gehäuse vor Wasser und Spritzwasser geschützt ist\n\nSCHRITT 5: App-Installation und Kopplung\n- Laden Sie die SMARTDOCK-App aus dem App Store oder Google Play Store herunter\n- Öffnen Sie die App und folgen Sie dem Einrichtungsassistenten\n- Aktivieren Sie Bluetooth auf Ihrem Smartphone\n- Suchen Sie nach dem SMARTDOCK-Gerät in der App\n- Koppeln Sie das Gerät durch Eingabe des Pairing-Codes (siehe Produktetikett)\n\nSCHRITT 6: Kalibrierung und Tests\n- Verbinden Sie die Batterie wieder mit dem Motor\n- Starten Sie den Motor und führen Sie einen Funktionstest durch\n- Überprüfen Sie alle Joystick- und Steuerfunktionen über die App\n- Kalibrieren Sie die Steuerung nach Bedarf\n\nSCHRITT 7: Abschluss und Dokumentation\n- Überprüfen Sie alle Verbindungen ein letztes Mal\n- Dokumentieren Sie die Installation mit Fotos\n- Bewahren Sie diese Anleitung für zukünftige Referenz auf\n- Registrieren Sie Ihr Gerät auf der SMARTDOCK-Website für Support",
    "titel_en": "Installation of SMARTDOCK for Volvo Penta twin-engine systems with EVC -C/-D/-E/2.0 joystick"
  },
  {
    "titel": "Installation von SMARTDOCK für Volvo Penta-Antriebe Doppelantrieb mit Joystick EVC -B/-C",
    "beschreibung": "SCHRITT 1: Sicherheitshinweise\n- Stellen Sie sicher, dass der Motor ausgeschaltet ist und sich abgekühlt hat\n- Tragen Sie geeignete Schutzausrüstung (Handschuhe, Schutzbrille)\n- Arbeiten Sie in einer gut belüfteten Umgebung\n- Lesen Sie alle Anweisungen vor Beginn durch\n\nSCHRITT 2: Vorbereitung\n- Sammeln Sie alle erforderlichen Werkzeuge und Materialien\n- Überprüfen Sie, dass alle Komponenten des SMARTDOCK-Systems vorhanden sind\n- Inspizieren Sie die Komponenten auf Beschädigungen\n\nSCHRITT 3: Elektrische Verbindungen\n- Trennen Sie die Batterie vom Motor\n- Identifizieren Sie die Joystick- und EVC-Anschlüsse am Volvo Penta-Doppelantrieb\n- Verbinden Sie das SMARTDOCK-Steuermodul gemäß dem Schaltplan für EVC -B/-C\n- Sichern Sie alle Kabelverbindungen mit Kabelbindern\n\nSCHRITT 4: Mechanische Installation\n- Montieren Sie das SMARTDOCK-Gehäuse an einem geschützten Ort\n- Verwenden Sie die mitgelieferten Befestigungsmaterialien\n- Stellen Sie sicher, dass das Gehäuse vor Wasser und Spritzwasser geschützt ist\n\nSCHRITT 5: App-Installation und Kopplung\n- Laden Sie die SMARTDOCK-App aus dem App Store oder Google Play Store herunter\n- Öffnen Sie die App und folgen Sie dem Einrichtungsassistenten\n- Aktivieren Sie Bluetooth auf Ihrem Smartphone\n- Suchen Sie nach dem SMARTDOCK-Gerät in der App\n- Koppeln Sie das Gerät durch Eingabe des Pairing-Codes (siehe Produktetikett)\n\nSCHRITT 6: Kalibrierung und Tests\n- Verbinden Sie die Batterie wieder mit dem Motor\n- Starten Sie den Motor und führen Sie einen Funktionstest durch\n- Überprüfen Sie alle Joystick- und Steuerfunktionen über die App\n- Kalibrieren Sie die Steuerung nach Bedarf\n\nSCHRITT 7: Abschluss und Dokumentation\n- Überprüfen Sie alle Verbindungen ein letztes Mal\n- Dokumentieren Sie die Installation mit Fotos\n- Bewahren Sie diese Anleitung für zukünftige Referenz auf\n- Registrieren Sie Ihr Gerät auf der SMARTDOCK-Website für Support",
    "titel_en": "Installation of SMARTDOCK for Volvo Penta twin-engine systems with EVC -B/-C joystick"
  },
  {
    "titel": "Installation von SMARTDOCK für Volvo Penta-Antriebe Einzelantrieb (EVC -D/-E)",
    "beschreibung": "SCHRITT 1: Sicherheitshinweise\n- Stellen Sie sicher, dass der Motor ausgeschaltet ist und sich abgekühlt hat\n- Tragen Sie geeignete Schutzausrüstung (Handschuhe, Schutzbrille)\n- Arbeiten Sie in einer gut belüfteten Umgebung\n- Lesen Sie alle Anweisungen vor Beginn durch\n\nSCHRITT 2: Vorbereitung\n- Sammeln Sie alle erforderlichen Werkzeuge und Materialien\n- Überprüfen Sie, dass alle Komponenten des SMARTDOCK-Systems vorhanden sind\n- Inspizieren Sie die Komponenten auf Beschädigungen\n\nSCHRITT 3: Elektrische Verbindungen\n- Trennen Sie die Batterie vom Motor\n- Identifizieren Sie die EVC-Anschlüsse am Volvo Penta-Einzelantrieb\n- Verbinden Sie das SMARTDOCK-Steuermodul gemäß dem Schaltplan für EVC -D/-E\n- Sichern Sie alle Kabelverbindungen mit Kabelbindern\n\nSCHRITT 4: Mechanische Installation\n- Montieren Sie das SMARTDOCK-Gehäuse an einem geschützten Ort\n- Verwenden Sie die mitgelieferten Befestigungsmaterialien\n- Stellen Sie sicher, dass das Gehäuse vor Wasser und Spritzwasser geschützt ist\n\nSCHRITT 5: App-Installation und Kopplung\n- Laden Sie die SMARTDOCK-App aus dem App Store oder Google Play Store herunter\n- Öffnen Sie die App und folgen Sie dem Einrichtungsassistenten\n- Aktivieren Sie Bluetooth auf Ihrem Smartphone\n- Suchen Sie nach dem SMARTDOCK-Gerät in der App\n- Koppeln Sie das Gerät durch Eingabe des Pairing-Codes (siehe Produktetikett)\n\nSCHRITT 6: Kalibrierung und Tests\n- Verbinden Sie die Batterie wieder mit dem Motor\n- Starten Sie den Motor und führen Sie einen Funktionstest durch\n- Überprüfen Sie alle Steuerfunktionen über die App\n- Kalibrieren Sie die Steuerung nach Bedarf\n\nSCHRITT 7: Abschluss und Dokumentation\n- Überprüfen Sie alle Verbindungen ein letztes Mal\n- Dokumentieren Sie die Installation mit Fotos\n- Bewahren Sie diese Anleitung für zukünftige Referenz auf\n- Registrieren Sie Ihr Gerät auf der SMARTDOCK-Website für Support",
    "titel_en": "Installation of SMARTDOCK for Volvo Penta single-drive systems (EVC -D/-E)"
  }
];

migrate(
  (app) => {
    for (const d of DATA) {
      let rec;
      try {
        rec = app.findFirstRecordByFilter("anleitungen", "titel = {:t}", { t: d.titel });
      } catch (e) {
        console.log("Anleitung not found, skipping: " + d.titel);
        continue;
      }
      rec.set("beschreibung", d.beschreibung);
      if (d.titel_en) rec.set("titel_en", d.titel_en);
      rec.set("aktiv", true);
      app.save(rec);
    }
  },
  (app) => {
    // no-op
  }
);
